name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1     
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: .
