name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup Python environment
      uses: actions/setup-python@v2
      
    - uses: actions/cache@v1
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: pip
        restore-keys: |
          pip
          
    - name: Install dependencies
      run: pip3 install jinja2
      
    - name: Build
      run: python3 scripts/generate.py 
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
